### ISSUE TITLE
Port all nodes under renderer mostly as is

### ISSUE THREAD

**Issue by kzys** [karino2/kotlitex#25]
Partially implemented
- [x] VerticalListRow
- [x] VerticalList

Not implemented at all
- [ ] BoxNode
- [x] HorizontalLineNode
- [x] HPaddingNode
- [x] StretchyNode
- [ ] SvgNode
- [ ] VerticalLineNode

@karino2 Can you take some of them? Sharing which one you want to tackle would prevent conflicts between us.

**Comment by karino2** [comment]
Do you know which one do we need to render x^2 propery?

**Comment by kzys** [comment]
VerticalListRow and VerticalList probably.

**Comment by karino2** [comment]
OK. I take VerticalList.

**Comment by karino2** [comment]
Most of VerticalList seems to have been already done and remaining part is not testable without VerticalListRow.
I also take some part of VerticalListRow.

**Comment by karino2** [comment]
It seems both of them does not contribute to render x^2 properly.
NYI part of VerticalList and VerticalListRow is only related to alignment, which is not used in x^2...

**Comment by karino2** [comment]
Maybe we should split these big issue now.

**Comment by kzys** [comment]
Let me review each node this weekend.

**Comment by karino2** [comment]
This issue becomes too abstract now.
Close this issue. Please create more specific small issue if you want.
