### ISSUE TITLE
Port VirtualNodeBuilder

### ISSUE THREAD

**Issue by kzys** [karino2/kotlitex#28]
VirtualNodeBuilder has the following methods, which are currently empty.

- [ ] extractClassDataFromNode(node)
- [x] extractStyleDataFromNode(node)
- [x] createMSpace()
- [ ] createSvgNode(node)
- [ ] createItalicNode(node)

**Comment by karino2** [comment]
I guess extractStyleDataFromNode is the main NYI part to support x^2.

**Comment by karino2** [comment]
I start createSvgNode porting (because I need it to verify expression tree).

**Comment by karino2** [comment]
Partially done.

**Comment by karino2** [comment]
This issue becomes too abstract now.
Close this issue. Please create more specific small issue if you want.
