### ISSUE TITLE
アプリをどこに作るか?

### ISSUE THREAD

**Issue by kzys** [karino2/kotlitex#3]
ゆくゆくは issues も英語にしたほうが使ってくれる人が増えていいかなあと思いつつ、まずは日本語で。

README から、このプロジェクトにはライブラリだけが入るつもりでいたんですが、アプリ部分ってどこに作ります? Kotlitex が最終的にアプリになるんだったら、sample とかモジュール分けずに全部 app に入れてしまったほうがシンプルで良さそう。

**Comment by karino2** [comment]
そうですねえ。そこはあんまり考えてなかった所です。
最終的にはライブラリとして公開したいので、アプリケーションとは分かれてた方がいいかなぁ。
そもそも現状appというのがたぶん良く無くて、このフォルダ名変えてちゃんとライブラリモジュールにした方が良い気はする。
（どこかのタイミングでやりたいが…）

現状はとりあえずどうしたもんですかね。
アプリはそちらが面倒で無ければsample下が良いですが、どの位面倒になるかは把握してません。面倒そうならくっつけちゃっても当面はＯＫです。

ただView関連はkotlitexの中が良いと思っています。
最終的にPaintのFontMetricsなどに依存するのは避けられないと思うので、View関連は分けないで行こう、と思ってました。
sample下はこのkotolitexの下のViewをActivityに置くだけ、程度にしたいと思っている。

**Comment by kzys** [comment]
sample から app に依存するときに、どっちもアプリケーションだとうまくいかなかったので、じゃあライブラリモジュールにするのはこっちでやっちゃいますね。app -> library のリネームは色々落ち着いてからでいいかな。

**Comment by karino2** [comment]
お、了解です。お願いします。

**Comment by karino2** [comment]
さきほどのPRでいったんこれは閉じちゃっていいですかね？

**Comment by kzys** [comment]
そうですね。Fixed by #5.
