### ISSUE TITLE
Move app -> library

### ISSUE THREAD

**Issue by kzys** [karino2/kotlitex#65]
I don't have any WIP branches to merge. Can we do that right now?

**Comment by karino2** [comment]
I agree it's time to do that.

**Comment by kzys** [comment]
Will do that then.

**Comment by kzys** [comment]
Regarding the name of the directory, how about `kotlitex` (instead of library)?

* https://github.com/JakeWharton/butterknife
* https://github.com/ReactiveX/RxAndroid

They follow the rule, and couldn't find a library that has `library` directory yet.

**Comment by karino2** [comment]
kotlitex seems better.
