### ISSUE TITLE
雑談

### ISSUE THREAD

**Issue by karino2** [karino2/kotlitex#7]
なんとなく思った事を書いておく所。
そのうち長くなり過ぎたら閉じる。

**Comment by karino2** [comment]
IssueはKazuyoshi Kato先生もおっしゃるようにそのうち英語にする方がいいと思うけれど、最初のライブラリをリリースする位までは日本語でいいかな、という気がする。

**Comment by karino2** [comment]
RenderNodeというのは名前が良く無いなぁ。
canvas-latexのVirtualCanvasNodesに相当するものがRenderNodeを名乗るのにふさわしいよなぁ。
この辺何かご意見あります？

あと、ParserNodeとRenderNodeは全く別の物だが、サブクラスの名前で判定出来ないのが辛い。
なんか名前の規則を作りたいが。

**Comment by karino2** [comment]
とりあえず大きなTODOをissueにして登録しておく。
この位が片付けばRenderTreeBuilderはひとまず完成でいい気がする。

#8 #9 #10 #11

**Comment by karino2** [comment]
ParserNodeのサブクラスはPNodeXX、RenderNodeのサブクラスはRNodeXXにするかなぁ。

**Comment by karino2** [comment]
ASのバージョン上げたらgradleのバージョン上げよ、と言われた。上げます。

**Comment by karino2** [comment]
fontMetricsの移植終了。
あとはdefineSymbol呼ぶ所と関数回りの処理を持って来ればまぁまぁちゃんと動くようになるが、関数回り持ってくるのが大変…
ま、気長にやっていきます。

**Comment by kzys** [comment]
Kotlin は

```
import foo
...
new foo.Bar
```

っての出来ないんですよね (Scala はできる)。だったら P/RNodeXX でいいかなあ。特に人の目に触れるものでもないし。

RenderNode もそのままで良いかと思いました。Layout という案を Twitter で書いてたと思うんですが、Layout だと Render より狭義のイメージ。

**Comment by karino2** [comment]
たぶんそういうimportは無いかなぁ（下位パッケージを作れば同じような記法には出来るが、アクセスできなくなったり副作用がある）。

了解です。PNodeXXとRNodeXXでとりあえずは行くかなぁ。

**Comment by karino2** [comment]
そういえばkatexのルートとかはsvgで描かれてて、SvgNodeというのがパスの情報を持ってるっぽい。
さすがにここはAndroid用に書き換えないとダメかなぁ。drawPolygon的なのがあった気はするのでそれに合わせるのが良さそうだけれど。

**Comment by karino2** [comment]
genfrac.jsのコード見てたら、makeLineSpanというので線を描いている。
spanのborderBottomとheightを調整して線っぽく見せている。
全部がSVGという訳じゃないのね。

Android的にはどうするのがいいかなぁ。
Spanで頑張らずに線を表すノードがある方が素直な気はするが、本当にそれで実装可能かが良く分かってない。

**Comment by karino2** [comment]
RNodeXX, PNodeXXへのリネーム、やりました。

関数が強敵でやる気が出ないのでその他簡単につぶせるTODOをつぶしておいた。

**Comment by karino2** [comment]
描画回りは自分はcanvas-latexのコードをそのままkotlinにもってきて最後のプラットフォームに依存する所だけ書き換えればいいかなぁ、と思ってたんですが、この路線はダメですかね？
あんまりコード真面目に読んでないので可能かどうかわかってないで言ってますが。

ツリーの各ノードの意味とか解読するのは大変なので、何も考えずに動くコードをもって来れるならそっちの方が良い気はしている。

**Comment by kzys** [comment]
canvas-latex 読みはじめました。

https://github.com/kzys/blog/blob/master/ja/content/post/2019/canvas-latex.md

これはレンダリングツリーっぽいの作ってる予感、って

> canvas-latexのVirtualCanvasNodesに相当するものがRenderNodeを名乗るのにふさわしいよなぁ。

SVG の件も含めてもう書いてましたね...

TextNode 周りのレンダリングだけ移植してみて様子を見るのがいいかなあ。canvas-latex は https://github.com/CurriculumAssociates/canvas-latex/blob/master/src/common/virtualCanvasNodes/TextNode.js#L27 とかで突然に隠しキャンバス使ってサイズ取得したりしてるんですが、この種のコードって既存の RNode 側にいれちゃいます?

**Comment by karino2** [comment]
ふーむ、どうですかね。
自分的にはレンダリングツリーっぽい物を別に作り直す方が良いかな、と思っていて、それを作る人がmeasure出来るのが正しいんじゃないか、という気がしていますが。

レンダリングだけ移植してみる、というのは、ツリーを新たに作り直さない路線で行こう、という話ですよね。

それはそれで構わないのだけど、そうおもう理由をまず聞きたい気がします。
というのはその路線だと、数式組版やtexのレイアウトの細かい仕様を理解する必要があるのでは？とおもうのですが、それは結構辛く無いですかね？

**Comment by karino2** [comment]
もう少し自分の思っている事を書いておきます。

**RNode側**

基本的にkatexと値を比較出来る、という状態は出来るだけ維持したい、と思っています。
という事で以下のような事を考えている。

- 追加で属性を増やすのはOK
- ノードを増やすのもOK
- 減らしたり置き換えるのは極力避けたい

置き換えはなるべくやりたくないけれど、必要なものは最小限やっていく、というつもりでいます。
例えばSvgNodeなどは置き換えた方が早いと思うので置き換えるつもりです。
現状は分数などの横線を置き換えるかどうかが悩んでるくらいの感覚です（今はSpanで書くコードのままで行くつもり）。

**ツリーをもう一つ作る方が良いと思っている話**

まずcanavs-latexが別のツリーを作っていて結構複雑な物がレンダリング出来ている、というのが一番大きな判断理由で、あれとなるべく同じ事をするのが確実と思っています。レイアウトが一体何をしているのかをちゃんと調べて理解するのは調査に膨大な時間がかかって全然進まなさそうなので、何も調べずに分かっている人が書いたコードをただまねる方が良いのでは、と。

ツリーをもう一本作る方が良いと思う他の理由としては、上で述べた通りの理由でRNode側をkatexと同じに維持するという選択を行っている為、このRNodeのツリーはhtmlレンダリングの仕組みに依存する場所があるのでは？と疑っている為です。
そこはAndroidのレンダリングの仕組みとは齟齬があるんじゃないかなぁ、と予想している（把握はしてません）。
だからRNodeを辿ってそのまま描くのは難しそうで、その齟齬を吸収する為に結局もう一本ツリー作るのは避けられないのでは無いか、というのが自分の考え。

katex側をちゃんと全部理解すればRNodeの所をそもそも最初からAndroidの描画用に書き換える方が良いけれど、生成されるツリーを見るとこれは非常に難しいのでやめた方が良いと思っている。

以上はRNode側しか見てないで判断した結論なので、もしcanvas-latexとか描画回りを調べたり考えた結果違う結論になっているなら、その辺の理由は知っておきたいと思っています。
（たぶん実際にやってみないと分からない事は多いと思うので）

**Comment by kzys** [comment]
「レンダリングだけ移植」は TextNode 周りだけ end-to-end で動くようにして、他の VirtualNode の移植は後回し、というつもりでした。canvas-latex と KaTeX のノードを統合するかどうかは自分でも迷っていたのですが、karino2 さんの分ける案は確かになるほどと思ったので、そっちの路線で行ってみます。

**Comment by karino2** [comment]
なるほど、TextNodeというノード自体は作るかどうか悩んでた、くらいでしたか。了解です。

やってみないと分からない見解はうまい事共有して進めていきたいと思ってます。
RNodeを作るまでやった側の印象としては「このツリーを全部理解するのはきつそうだな」というのが得られた知見です。
レンダリング側やってみた結果なにか知見が得られたら教えてくだされ～

**Comment by karino2** [comment]
ここまで来ると結構いけそうな気もする。
とりあえずx^2をちゃんとした位置に表示してみる、が次の目標ですかねぇ。

**Comment by karino2** [comment]
結果としてはVirtualCanvasNodeはもうx^2を表示するには十分な所まで終わっていそうだった。
まぁこういうのはやってみないと分からないので仕方ない。
ただそろそろx^2は表示出来そうな気がする。

現状のTODOは全残り作業、みたいな粒度だけど、これの他に次のマイルストーンまでのTODOも作りたい気がする（最初は何が必要か分かってないので作れないですが）

マイルストーンとしては以下みたいなイメージで進めたいと思っていますがどうでしょう？

1. x^2を正しくレンダリングする
2. \frac{1}{2}を正しくレンダリングする
3. \sqrt{3} を正しくレンダリングする
4. \sum_{k=0}^{N} k^2 を正しくレンダリングする

1でとりあえずbuildExpressionで十分な情報を持っている、というのを確認したい。
2でbox回りで横線引く、という路線を真似してＯＫかを確認したい。
3でsvg回りをどうするかを決めたい。
4はなんとなくこの位までレンダリング出来たら凄そう、程度。

なおRNode側は2までは（一応）終わってます。

とりあえず1を終えるまでに必要な最小限のタスクを知りたいけど、たぶんあとextractStyleDataFromNodeだけかな？甘い？

**Comment by karino2** [comment]
とりあえず自分は1が終わるまではVirtualCanvasNode側はもういじらない事にします。（だいたい感じは分かったので）

1が終わったら、2をやる時にまた一つくらい手伝いたい。
2の作業のToDoが洗い出せたらなんか良さそうなのを一つください。

**Comment by kzys** [comment]
うーん、なるほど。size3 も昨日実装したのであと上付 (sup) が足りないんですよね。もうちょっとみてみます。

マイルストーンはそれで良さそうなので、一旦それで GitHub 上にマイルストーン作れます? 多分レポジトリの管理者じゃないと作れないはず。

**Comment by karino2** [comment]
4はまぁちょっとまだ良く分からないので、3までのマイルストーンを作ってみました。
自分の印象では4くらいまで行ったら外部にアナウンスしてもいいかな、と思ってます（別に今も秘密にしてる訳じゃないが…）。

なお、フォントのサポートはどこかでやる必要がありますが、とりあえずどこかでやればいいか、くらいに思っていて1には含めていません。

M1を終えるのに必要な残りタスク、分かったものがあれば随時issueに上げてM1のマイルストーンに紐づけてください。とりあえずextractStyleDataFromNodeを作ってみました( #31 )

**Comment by karino2** [comment]
ちょっと暇が出来たので、やっぱりextractStyleDataFromNodeをやってみます。すでに手を付けてたらすみません。

**Comment by kzys** [comment]
実は手をつけてて `x^2` レンダリングできるようになりました :)

**Comment by karino2** [comment]
お、素晴らしい。確認してみます。

**Comment by karino2** [comment]
margin-rightっていらないんですかね？buildExpressionの結果には入ってそうですが。

**Comment by kzys** [comment]
`x^2` だと `2` が入ってるほうの span についていて、そのあとにレンダリングするものがないので、今は必要なさそうです。

**Comment by karino2** [comment]
なるほど。
レンダリング結果見ました。良さそう。
M1はcloseします。

**Comment by karino2** [comment]
M2向けのhtmlのダンプ結果を入れておきます。
https://github.com/karino2/kotlitex/blob/master/dumpresult.txt

これを眺めると、

Styleは

- border-bottom-width
- height

CSSは

- frac-line

に対応すれば正しく表示されそう？（わからないけれど）

**Comment by karino2** [comment]
開発中のViewとしてはどうしましょうかね。
元の物も表示しておく方が良い気はする。

二つView貼って、下がx^2、上がfrac、とかでいいかしら？

**Comment by kzys** [comment]
2つ view はるので良いと思います。本当はテスト書いて壊れないこと保証しないといけないんだけど、まあそれはおいおい。

**Comment by karino2** [comment]
そうですね。じゃあそんな感じで行きましょう。
なんかM2もすぐ終わってしまいそうな気がするので、こちらはRNode側のsqrtとSVG Node回りの作業に取り掛かります。

**Comment by karino2** [comment]
おぉ、fracも終わりですね。
もう結構レンダリング側は完成してきたかしら？

マイルストーンには設定してなかったですが、せっかくなので今までサポートしたものの複雑な組み合わせを動かしておきたいな、という気がしています。
試しに以下をやったら私の所で落ちる。(#40 )

\frac{1}{1+\frac{1}{x^2}}

たぶん未サポートなノードを追加していくだけで割と簡単に出来ると期待しているが…

とりあえず自分はSvgNodeに取り掛かってしまったのでこのまま続けます。
終わった後にやるかもしれませんが、もし興味があったらそっちでやってみてくれると嬉しいかも。

**Comment by karino2** [comment]
う、sqrtが思った以上に大変だ…
時間掛けてちょっとずつ進めます。

**Comment by karino2** [comment]
横に線が、間違った場所に表示されるようにはなりました。
何が悪いのか分かりませんが、Pathオブジェクトが一応は生成されて描画されるようにはなったので、ひとまずここまででmergeします。

チケットを切るので、そちらでレンダリング側見てみてもらえますか？
とりあえず手でrCubicToして曲線を描くのがうまくいってない気がする（すごく横に長いのなら直線が描かれたが…）

**Comment by karino2** [comment]
作りました #43

**Comment by karino2** [comment]
あ、これcloseした時に別に作り直さなきゃいけない仕様なのかも。
ちょっと自分で調査してみます。

**Comment by karino2** [comment]
ダメでした。どうもrCubicToを描く事が出来ていない気がします。
arcToは出るので曲線が出ない訳でもなさそうだけど…
Paintに何か設定し忘れがあるのかなぁ。

**Comment by karino2** [comment]
どうもscalingが間違っている模様。slice相当の処理を書かないといけないが、現状はmeetになってるっぽい。

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/preserveAspectRatio
https://developer.android.com/reference/android/graphics/Matrix.ScaleToFit

**Comment by karino2** [comment]
形はちゃんとレンダリングされるようになりました。
位置がおかしいですが、ここからはそちらで直す方が早そうなのでお願いしたい。

現状CanvasNode側(というのか？呼び名不明ですが）で必要な所は、とりあえず動く範囲で実装しました。
例えばpreserveAspectRatioは文字列になってますが、enumのsetの方が良さそう、とか、widthStrとheightStrというのを作ったけれど、この辺はもうちょっとコードを良く調べて必要かどうか考えた方がいい、とか手抜きな所はちょこちょこあるので、その辺もお願いします。

**Comment by karino2** [comment]
複雑な分数もサポートしてみました。
ちょっとレンダリングはおかしいですが、とりあえず表示される所までは行った。
レンダリングについてはissueを作っておきましたが( #47 )、とりあずルートが先かなぁ。
この辺の問題を取り組む時にはkatexフォントの組み込みとかを視野にいれてもいいかもしれませんなぁ。

結構いい所まで来てるんじゃないかしら？

**Comment by karino2** [comment]
katex.cssを見て、sizeとreset_sizeを1から11まで定義してみた。
kotlin的にはsize1, size2, size3...とするよりも、sizeNとして値に1とか2とか3とかを持たせる方が良いかもなぁ。
この辺はClassStateMapping側と合わせて考えるべきか。

**Comment by karino2** [comment]
何も理解せずにClassStateMappingのcaseをひたすらコピペで追加したらfracの表示が治った？
マージンとかがおかしい気もするけれど、この辺は現時点ではまだいいかなぁ、と思うので #47 はfixで。

**Comment by karino2** [comment]
M4 sum, prodと、M5 これまでサポートしたものの組み合わせを一通り動かす、の二つのマイルストーンを追加しました。
M5まで終わったら一般にアナウンスしようかと思っています（といってもどうアナウンスするかとかはno ideaです）。

**Comment by karino2** [comment]
sumとprodに関して、ツリーの生成の部分が正しいかを検証するよりもちゃんとレンダリングする過程でデバッグしていく方が早そうなので、sumのレンダリングをやってみようと思います。 (#53)

たぶん大した事無いと思っているのだが…

**Comment by karino2** [comment]
マージンが少しあいてますが、この辺はフォントのせいかもしれないので、katex fontをちゃんと組み込むのを先にやってから調整する方がいいかな、と思います。

![normalappimage 8](https://user-images.githubusercontent.com/1468643/52521097-45026b80-2cb5-11e9-90d6-67806546bcd3.png)

という事でレンダリングは何もいじってないですが、だいたいレンダリング出来てました。

**Comment by karino2** [comment]
長くなってきたので作り直し。
