### ISSUE TITLE
CssFont and FontLoader integration

### ISSUE THREAD

**Issue by karino2** [karino2/kotlitex#85]
Currently, #84 is very dirty integration of CssFont and FontLoader.

For example, I do not handle variant.
And inside updateSize(), I use Typeface.SERIF, and the result of measure must be wrong.

For FontLoader, we need AssetManager.
We need to better orgnalize CssFontFamily-CssFont-FontLoader.

**Comment by kzys** [comment]
Will do, but probably in later next week.

**Comment by karino2** [comment]
Can I close this issue with #88 ?
Sigma symbol seems to place a little too left, but it might be different issue.

**Comment by kzys** [comment]
Wait a sec.  I have a new PR to handle variants

**Comment by kzys** [comment]
Okay #89 can resolve this issue.

**Comment by karino2** [comment]
Done.
